debug: false
httpport: 8080
github:
  admin: "xxxxxx" #管理员 GitHub ID，复制自己GitHub头像图片地址，/[ID].png 多个用英文逗号隔开
  clientid: "xxxxxxxxxxxxxx" # 在 https://github.com/settings/developers 创建，无需审核 Callback 填 http(s)://域名或IP/oauth2/callback
  clientsecret: "xxxxxxxxxxxxxxxxxxxx"
site:
  brand: "nz_site_title"
  cookiename: "nezha-dashboard" #浏览器 Cookie 字段名，可不改
