debug: true
httpport: 8080
github:
  admin: "8230646" #管理员 GitHub ID，复制自己GitHub头像图片地址，/[ID].png 多个用英文逗号隔开
  clientid: "ddb573b49a8f2ea756ff" # 在 https://github.com/settings/developers 创建，无需审核 Callback 填 http(s)://域名或IP/oauth2/callback
  clientsecret: "5706276a997f0af3ed2b09582d3e2395eed73ba0"
site:
  brand: "nz_site_title"
  cookiename: "nezha-dashboard" #浏览器 Cookie 字段名，可不改
